spring:
  freemarker:
    suffix: ".ftl"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/bybook}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}