spring:
  freemarker:
    suffix: ".ftl"
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: ${DB_URL:jdbc:mysql://localhost:3306/bookstore}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:root}